import React, { useState, useEffect } from 'react';
import { View, StyleSheet, TouchableOpacity, Image, Alert } from 'react-native';
import { Text } from "../../components/globalText";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { WebView } from 'react-native-webview';
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import { db, auth } from "../../firebase";
import { doc, getDoc } from "firebase/firestore";
import QRCode from "react-native-qrcode-svg";

export default function TicketGen() {
    const router = useRouter();
    const { orderId } = router.params || {};

    const [orderData, setOrderData] = useState(null);
    const [userName, setUserName] = useState('');
    const [qrSvg, setQrSvg] = useState('');

    useEffect(() => {
        if (orderId) {
            fetchOrderData();
        }
    }, [orderId]);

    const fetchOrderData = async () => {
        try {
            const orderDoc = await getDoc(doc(db, "cartItems", orderId));
            if (orderDoc.exists()) {
                const data = orderDoc.data();
                setOrderData(data);
                
                // Format date
                const orderDate = data.createdAt?.toDate() || new Date();
                data.formattedDate = orderDate.toLocaleDateString();
                data.formattedTime = orderDate.toLocaleTimeString();
                
                // In a real app, you would fetch user name from users collection
                setUserName("Customer"); // Replace with actual user name fetch
            }
        } catch (error) {
            console.error("Error fetching order data: ", error);
        }
    };

    const generatePDFHtml = () => {
        if (!orderData) return '';

        const total = orderData.items.reduce((sum, item) => sum + (item.price * item.quantity), 0);

        return `
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <title>Order Ticket</title>
                <style>
                    body { 
                        font-family: Arial, sans-serif; 
                        margin: 0; 
                        padding: 20px; 
                        background: white;
                    }
                    .ticket { 
                        border: 2px solid #333; 
                        padding: 20px; 
                        max-width: 400px; 
                        margin: 0 auto;
                    }
                    .header { 
                        text-align: center; 
                        margin-bottom: 20px; 
                        border-bottom: 1px solid #333; 
                        padding-bottom: 10px;
                    }
                    .qr-container { 
                        text-align: center; 
                        margin: 20px 0; 
                    }
                    .order-info { 
                        text-align: center; 
                        margin: 10px 0; 
                    }
                    .customer-info { 
                        margin: 15px 0; 
                        padding: 10px; 
                        background: #f5f5f5; 
                    }
                    .items-table { 
                        width: 100%; 
                        border-collapse: collapse; 
                        margin: 15px 0; 
                    }
                    .items-table th, .items-table td { 
                        border: 1px solid #333; 
                        padding: 8px; 
                        text-align: left; 
                    }
                    .items-table th { 
                        background: #f0f0f0; 
                    }
                    .total { 
                        text-align: right; 
                        font-weight: bold; 
                        font-size: 16px; 
                        margin-top: 15px;
                    }
                    .footer { 
                        text-align: center; 
                        margin-top: 20px; 
                        font-size: 12px; 
                        color: #666;
                    }
                </style>
            </head>
            <body>
                <div class="ticket">
                    <div class="header">
                        <h1>ORDER TICKET</h1>
                    </div>
                    
                    <div class="qr-container">
                        <!-- QR Code will be generated by React Native -->
                        <div style="text-align: center; margin: 20px 0;">
                            <p>QR Code displayed in app</p>
                        </div>
                    </div>
                    
                    <div class="order-info">
                        <p><strong>ORDER ID:</strong> ${orderId}</p>
                        <p><strong>DATE:</strong> ${orderData.formattedDate}</p>
                        <p><strong>TIME:</strong> ${orderData.formattedTime}</p>
                    </div>
                    
                    <div class="customer-info">
                        <p><strong>Customer Name:</strong> ${userName}</p>
                        <p><strong>Payment Method:</strong> ${orderData.paymentMethod}</p>
                    </div>
                    
                    <table class="items-table">
                        <thead>
                            <tr>
                                <th>Item Code</th>
                                <th>Category</th>
                                <th>Size</th>
                                <th>Qty</th>
                                <th>Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${orderData.items.map(item => `
                                <tr>
                                    <td>${item.itemCode}</td>
                                    <td>${item.category}</td>
                                    <td>${item.size}</td>
                                    <td>${item.quantity}</td>
                                    <td>₱${item.price}</td>
                                </tr>
                            `).join('')}
                        </tbody>
                    </table>
                    
                    <div class="total">
                        TOTAL: ₱${total}
                    </div>
                    
                    <div class="footer">
                        <p>Thank you for your order!</p>
                    </div>
                </div>
            </body>
            </html>
        `;
    };

    const downloadPDF = async () => {
        try {
            const htmlContent = generatePDFHtml();
            const fileName = `order_ticket_${orderId}.pdf`;
            
            // For now, we'll share as HTML since PDF generation requires more setup
            const fileUri = `${FileSystem.documentDirectory}${fileName}.html`;
            await FileSystem.writeAsStringAsync(fileUri, htmlContent);
            
            if (await Sharing.isAvailableAsync()) {
                await Sharing.shareAsync(fileUri, {
                    mimeType: 'text/html',
                    dialogTitle: 'Download Order Ticket'
                });
            } else {
                Alert.alert('Success', 'Ticket saved to device');
            }
        } catch (error) {
            console.error('Error saving ticket:', error);
            Alert.alert('Error', 'Failed to save ticket');
        }
    };

    if (!orderData) {
        return (
            <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
                <Text>Loading ticket...</Text>
            </View>
        );
    }

    return (
        <View style={{ flex: 1, backgroundColor: "#FFFBFB" }}>
            <View style={styles.container}>
                {/* Header */}
                <View style={styles.header}>
                    <TouchableOpacity onPress={() => router.push("/dash_mod/transact")}>
                        <Ionicons name="close" size={28} color="black" />
                    </TouchableOpacity>
                </View>

                {/* Ticket Preview */}
                <View style={styles.ticketPreview}>
                    <View style={styles.ticket}>
                        <View style={styles.ticketHeader}>
                            <Text style={styles.headerTitle}>ORDER TICKET</Text>
                        </View>
                        
                        {/* QR Code */}
                        <View style={styles.qrContainer}>
                            {orderId && (
                                <QRCode 
                                    value={orderId} 
                                    size={200}
                                    getRef={(c) => {
                                        if (c) {
                                            // QR code is displayed natively
                                        }
                                    }}
                                />
                            )}
                        </View>
                        
                        {/* Order Info */}
                        <View style={styles.orderInfo}>
                            <Text style={styles.infoText}><Text style={styles.label}>ORDER ID:</Text> {orderId}</Text>
                            <Text style={styles.infoText}><Text style={styles.label}>DATE:</Text> {orderData.formattedDate}</Text>
                            <Text style={styles.infoText}><Text style={styles.label}>TIME:</Text> {orderData.formattedTime}</Text>
                        </View>
                        
                        {/* Customer Info */}
                        <View style={styles.customerInfo}>
                            <Text style={styles.infoText}><Text style={styles.label}>Customer Name:</Text> {userName}</Text>
                            <Text style={styles.infoText}><Text style={styles.label}>Payment Method:</Text> {orderData.paymentMethod}</Text>
                        </View>
                        
                        {/* Items Table */}
                        <View style={styles.itemsContainer}>
                            <View style={styles.tableHeader}>
                                <Text style={styles.tableHeaderText}>Item Code</Text>
                                <Text style={styles.tableHeaderText}>Category</Text>
                                <Text style={styles.tableHeaderText}>Size</Text>
                                <Text style={styles.tableHeaderText}>Qty</Text>
                                <Text style={styles.tableHeaderText}>Price</Text>
                            </View>
                            
                            {orderData.items.map((item, index) => (
                                <View key={index} style={styles.tableRow}>
                                    <Text style={styles.tableCell}>{item.itemCode}</Text>
                                    <Text style={styles.tableCell}>{item.category}</Text>
                                    <Text style={styles.tableCell}>{item.size}</Text>
                                    <Text style={styles.tableCell}>{item.quantity}</Text>
                                    <Text style={styles.tableCell}>₱{item.price}</Text>
                                </View>
                            ))}
                        </View>
                        
                        {/* Total */}
                        <View style={styles.totalContainer}>
                            <Text style={styles.totalText}>
                                TOTAL: ₱{orderData.items.reduce((sum, item) => sum + (item.price * item.quantity), 0)}
                            </Text>
                        </View>
                        
                        <View style={styles.footer}>
                            <Text style={styles.footerText}>Thank you for your order!</Text>
                        </View>
                    </View>
                </View>

                {/* Download Button */}
                <View style={styles.btn_cont}>
                    <TouchableOpacity style={styles.dlbtn} onPress={downloadPDF}>
                        <Image
                            source={require("../../assets/images/icons/gen_icons/download.png")}
                            style={styles.icon_img}
                        />
                        <Text style={styles.btn_txt}>Download Ticket</Text>
                    </TouchableOpacity>
                </View>
            </View>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
    },
    header: {
        flexDirection: "row",
        justifyContent: "flex-end",
        alignItems: "center",
        marginBottom: 20,
    },
    ticketPreview: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    ticket: {
        borderWidth: 2,
        borderColor: '#333',
        padding: 20,
        backgroundColor: 'white',
        width: '100%',
        maxWidth: 400,
    },
    ticketHeader: {
        alignItems: 'center',
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#333',
        paddingBottom: 10,
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: 'bold',
    },
    qrContainer: {
        alignItems: 'center',
        marginVertical: 20,
    },
    orderInfo: {
        alignItems: 'center',
        marginVertical: 10,
    },
    customerInfo: {
        backgroundColor: '#f5f5f5',
        padding: 10,
        marginVertical: 10,
        borderRadius: 5,
    },
    infoText: {
        fontSize: 14,
        marginVertical: 2,
    },
    label: {
        fontWeight: '600',
    },
    itemsContainer: {
        marginVertical: 15,
    },
    tableHeader: {
        flexDirection: 'row',
        backgroundColor: '#f0f0f0',
        padding: 8,
        borderWidth: 1,
        borderColor: '#333',
    },
    tableHeaderText: {
        flex: 1,
        fontWeight: '600',
        fontSize: 12,
    },
    tableRow: {
        flexDirection: 'row',
        padding: 8,
        borderWidth: 1,
        borderColor: '#333',
        borderTopWidth: 0,
    },
    tableCell: {
        flex: 1,
        fontSize: 12,
    },
    totalContainer: {
        alignItems: 'flex-end',
        marginTop: 15,
    },
    totalText: {
        fontWeight: 'bold',
        fontSize: 16,
    },
    footer: {
        alignItems: 'center',
        marginTop: 20,
    },
    footerText: {
        fontSize: 12,
        color: '#666',
    },
    btn_cont: {
        alignItems: 'center',
        marginTop: 20,
    },
    dlbtn: {
        backgroundColor: '#61C35C',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        width: 200,
        height: 50,
        gap: 10
    },
    icon_img: {
        height: 20,
        width: 20
    },
    btn_txt: {
        fontWeight: '500',
        fontSize: 16,
        color: 'white'
    }
});